### PR TITLE
fergus plz halp

### PR DESCRIPTION
**Pull request by Shellywell123**

### CODE REVIEW

**Comment by Shellywell123** [comment]
@fjebaker this what you were after?

**Review by JR-Mitchell — APPROVED** [review]
Nice :) in a perfect world the `sendKey` function would probably be in a separate file, but we gotta go fast :shipit:

**Review by fjebaker — APPROVED** [review]
:shipit:

**Comment by Shellywell123** [comment]
https://www.youtube.com/watch?v=yqyQ5I6TSck&ab_channel=%F0%9D%97%99%F0%9D%97%A2%F0%9D%97%A9%F0%9D%97%98%F0%9D%97%94%7C%F0%9D%97%9A%F0%9D%97%A5%F0%9D%97%98%F0%9D%97%98%F0%9D%97%A1%F0%9D%97%A6%F0%9D%97%96%F0%9D%97%A5%F0%9D%97%98%F0%9D%97%98%F0%9D%97%A1%F0%9D%97%A0%F0%9D%97%98%F0%9D%97%A0%F0%9D%97%98

**Pull request merged**
